runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: gunicorn -t 1200 -b :$PORT main:app

inbound_services:
- warmup

resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 40

handlers:
- url: /_ah/warmup
  script: main.py
